### ISSUE TITLE
AEX-2 - passing config data to the wallet ?

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/AEXs#140]
Looking at the browser wallet implementation example [here](https://github.com/aeternity/aepp-sdk-js/blob/develop/docs/guides/how-to-build-aepp.md), in the initialization process there are URLs to nodes and compiler being provided. Can someone please confirm, that those values are serving whatever purpose and are **not** being used by the superhero wallet ? (I don't have a node at my disposal right now and therefore can't check myself unfortunately, also I can't find info in the addon about the compiler URL).

**Comment by marc0olo** [comment]
isn't it possible to quickly check that by switching to a local network in the superhero wallet? or using some "nonsense" network in the superhero wallet which would result an error when trying to call a contract which e.g. is only deployed on testnet?

if still the provided config is being used (which hopefully shouldn't be the case) then this is definitely a problem.

otherwise we should revisit the initialization of the `RpcAepp` in the SDK. do we really need to pass an initial config for node (and compiler) there? if so, why?

sidenotes:
- I think that discussion is better placed in the repo of the repo of the javascript sdk as you are talking about a specific implementation
- the AEX-2 proposal has been withdrawn anyway. but yeah, it's implemented in the javascript sdk

**Comment by nikita-fuchs** [comment]
Contrary to my prior observations, the SH wallet integration requires this information to be present as I could confirm today.

If the code is 
```
this.Chain = await RpcAepp({
    name: 'AEPP',
    nodes: [
      {name: 'ae_mainnet', instance: await Node({url: this.MAINNET_URL})},
      {name: 'ae_uat', instance: await Node({url: this.TESTNET_URL})}
    ],
```

and you comment out the `nodes` and `compilerUrl` field and you initialize the web wallet you are greeted with the following error:
    
   ` Error: Uncaught (in promise): Error: Node with name ae_mainnet not in pool`

which shouldn't be an information provided client-side, but taken from the browser wallet.

**Comment by marc0olo** [comment]
this is an implementation specific question and discussion. please continue in https://github.com/aeternity/aepp-sdk-js/issues/1255

closing this here now. want to clean up the whole repository. lot's of issues that all refer to the same AEX proposals. very unclear and confusing for everybody.
